# docker build -t aprojection:v2 ./ -f Dockerfile-like-chrome

# Base docker image
FROM debian:sid-slim
MAINTAINER Dzmitry Hlukhau 'dzmitry.hlukhau@outlook.com'


FROM debian:sid-slim
LABEL maintainer "Jessie Frazelle <jess@linux.com>"

RUN	apt-get update && apt-get install -y \
	ca-certificates \
	dirmngr \
	gnupg \
	alsa-utils \
	libgl1-mesa-dri \
	libgl1-mesa-glx \
	libpulse0 \
	libsm6 \
    python3 \
    pip \
    python3-dev \
    libasound2-dev \
	xdg-utils \
    mplayer \
    lirc \
    pulseaudio \
    lsof

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir -r requirements.txt


CMD ["python3", "./admin.py"]
